Query:
  type: object
  config:
    description: 'Collmex API repository'
    fields:
      delivery:
        type: "Delivery"
        args:
          client_id:
            description: Client ID
            type: Int
          delivery_id:
            description: Delivery ID
            type: Int!
        resolve: "@=resolver('Delivery', [args['client_id'], args['delivery_id']])"
      delivery_raw:
        type: "[DeliveryRaw]"
        args:
          client_id:
            description: Client ID
            type: Int
          delivery_id:
            description: Delivery ID
            type: Int!
        resolve: "@=resolver('DeliveryRaw', [args['client_id'], args['delivery_id']])"
      #      products:
      #        type: '[Product]'
      #        resolve: "@=resolver('Products')"
      product:
        type: "Product"
        args:
          client_id:
            description: Client ID
            type: Int
          product_id:
            description: SKU
            type: String!
        resolve: "@=resolver('Product', [args['client_id'], args['product_id']])"
      product_raw:
        type: "ProductRaw"
        args:
          client_id:
            description: Client ID
            type: Int
          product_id:
            description: SKU
            type: String!
        resolve: "@=resolver('ProductRaw', [args['client_id'], args['product_id']])"