# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    collmex.api.customer_id: '%env(COLLMEX_API_CUSTOMER_ID)%'
    collmex.api.user: '%env(COLLMEX_API_USER)%'
    collmex.api.password: '%env(COLLMEX_API_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\Collmex\ApiClient\BaseRequest\BaseRequestInterface:
        factory: ['App\Repository\Collmex\ApiClient\BaseRequest\BaseRequestFactoryInterface', 'createBaseRequest'];

    App\Repository\Collmex\ApiClient\Type\Sales\Delivery\DeliveryRequestInterface:
        factory: [ 'App\Repository\Collmex\ApiClient\BaseRequest\BaseRequestFactoryInterface', 'createBaseRequest' ];

    App\Repository\Collmex\ApiClient\ApiClientConfig:
        arguments:
            $customerId: '%collmex.api.customer_id%'
            $apiUser: '%collmex.api.user%'
            $apiPassword: '%collmex.api.password%'
